---
- name: disk remediation playbook
  hosts: all
  gather_facts: no
  vars:
    relative_time: "day"
    commentuser: "Nott"

  tasks:
    - name: push comment to dynatrace
      url:
        url: "{{ problemUrl }}"
        method: POST
        body_format: json
        body: '{ "comment": "Disk remediation playbook started.", "{{commentuser}}", "context": "Ansible Tower" }'
        when: state is defined and state == "OPEN"
    
    - name: cleaning application
      debug:
        msg: "Cleaning log files"
    - name: "Cleaning files"
      become: true
      become_user: root
      shell: |
        chmod +rx /home/dtu_training/ansible/roles/app-disk-filler/files/disk-cleaner.sh
        /home/dtu_training/ansible/roles/app-disk-filler/files/disk-cleaner.sh /home/dtu_training/storage
      register: result
    - debug: msg="{{ result.stdout }}"
    
    - name: push comment to dynatrace
      url:
        url: "{{ problemUrl }}"
        method: POST
        body_format: json
        body: '{"comment": "Disk remediation successful.", "user" "{{commentuser}}", "context": "Ansible Tower"}'
        when: state is defined and state == "OPEN"
