---
- name: disk remediation playbook
  hosts: all
  gather_facts: no
  vars:
    relative_time: "day"
    commentuser: "Nott"

  tasks:
    - name: push comment to dynatrace
      uri:
        url: "{{ problemUrl }}"
        method: POST
        body_format: json
        body: '{ "comment": "Disk remediation playbook started.", "{{commentuser}}", "context": "Ansible Tower" }'
      when: state is defined and state == "OPEN"
    
    - name: cleaning application
      debug:
        msg: "{{ problemUrl }}"
    - name: "Delete file(s)"
      become: true
      become_user: root
      file:
        path: /home/ubuntu/testdisk/abc.text
        state: absent
      register: result
    - debug: msg="{{ result.stdout }}"
    
    - name: push comment to dynatrace
      uri:
        url: "{{ problemUrl }}"
        method: POST
        body_format: json
        body: '{"comment": "Disk remediation successful.", "user" "{{commentuser}}", "context": "Ansible Tower"}'
      when: state is defined and state == "OPEN"
